# Generated by Django 5.2.1 on 2025-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_jobapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='amount',
            field=models.CharField(blank=True, null=True),
        ),
    ]
