# Generated by Django 5.2.1 on 2025-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
